export const PAYMENT_METHOD_TYPES = {
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  MOBILE_PAY: 'MOBILE_PAY',
  POINT: 'POINT',
} as const;

export type PaymentMethodType = (typeof PAYMENT_METHOD_TYPES)[keyof typeof PAYMENT_METHOD_TYPES];

export const PAYMENT_PROVIDER_IDS = {
  KAKAO_PAY: 'KAKAO_PAY',
  KOOKMIN_BANK: 'KOOKMIN_BANK',
  KOOKMIN_CARD: 'KOOKMIN_CARD',
  NAVER_PAY: 'NAVER_PAY',
  POINT_SYSTEM: 'POINT_SYSTEM',
  SAMSUNG_PAY: 'SAMSUNG_PAY',
  SHINHAN_BANK: 'SHINHAN_BANK',
  SHINHAN_CARD: 'SHINHAN_CARD',
  TOSS_PAY: 'TOSS_PAY',
} as const;

export type PaymentProviderId = (typeof PAYMENT_PROVIDER_IDS)[keyof typeof PAYMENT_PROVIDER_IDS];
