name: Assign Reviewers
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          reviewers: wonill,MSbtff,Rndns,aaa67,akssw9120
          max-num-of-reviewers: 2
