name: Sync GitHub Labels

on:
  push:
    paths:
      - '.github/labels.yml'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  label-sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write # 라벨 생성/수정 권한
      pull-requests: write # PR 라벨 수정을 위한 권한
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels with micnncim/action-label-syncer
        uses: micnncim/action-label-syncer@v1
        env:
          # 직접 만든 PAT 대신, GitHub Actions가 기본 제공하는 안전한 토큰을 사용합니다.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 이 액션은 설정 파일 파라미터 이름이 'manifest' 입니다.
          manifest: .github/labels.yml
          # 이 옵션을 true로 설정해야 yml 파일에서 삭제된 라벨이 저장소에서도 삭제됩니다.
          prune: true
