name: Sync GitHub Labels

on:
  push:
    paths:
      - '.github/labels.yml'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  label-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # 레이블 생성 권한
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.AHNTECH }}
          config-file: '.github/labels.yml'
